version: "3"

services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./mysql:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - node-mysql-net

    node:
        build: ./node
        entrypoint: dockerize -wait tcp://mysql:3306 node index.js
        volumes:
            - ./node:/home/node/app
            - /home/node/app/node_modules
        depends_on:
            - mysql
        networks:
            - node-nginx-net
            - node-mysql-net

    nginx:
        build: ./nginx
        entrypoint: dockerize -wait http://node:3000 /docker-entrypoint.sh nginx -g 'daemon off;'
        #command: nginx -g 'daemon off;'
        ports: 
            - 8000:80
        depends_on: 
            - node
        networks:
            - node-nginx-net
        
networks:
    node-nginx-net:
        driver: bridge
    node-mysql-net:
        driver: bridge


        